import { useEffect, useMemo, useState } from 'react'
import type { EncounterAbilityBreakdown, EncounterRecord } from '../types/database'
import '../App.css'

const triggered=new Set(['ykesha','blood siphon strike','blood draw strike','asp venom strike','cobra venom strike','weakening strike','hobbling strike','befuddling strike','concussive strike','clumsiness strike','banishing strike'])
const special=new Set(['backstab','bash','kick','reave','slam','frenzy','gore','smash','rend','sting','maul','bite','claw'])
const norm=(v:string)=>v.trim().toLowerCase()
function category(a:EncounterAbilityBreakdown){const n=norm(a.ability); if(a.actorType==='pet')return 'Pet'; if(triggered.has(n))return 'Triggered Effects'; if(a.source==='melee'&&special.has(n))return 'Special Attacks'; if(a.source==='melee')return 'Melee'; if(a.source==='dot')return 'DoTs'; if(a.source==='damage-shield')return 'Damage Shield'; return 'Spells / Effects'}
function dur(ms:number){const s=Math.round(ms/1000),m=Math.floor(s/60);return m?m+'m '+(s%60)+'s':s+'s'}
export default function StatisticsPage(){
 const [rows,setRows]=useState<EncounterRecord[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState('')
 useEffect(()=>{let dead=false; window.electronAPI.listEncounters(5000).then(r=>{if(!dead)setRows(r)}).catch(e=>{console.error(e);if(!dead)setError('Unable to load combat analytics.')}).finally(()=>{if(!dead)setLoading(false)}); return()=>{dead=true}},[])
 const a=useMemo(()=>{const fights=rows.filter(x=>x.outcome==='victory'),covered=fights.filter(x=>x.abilities.length); const total=fights.reduce((n,x)=>n+x.totalDamage,0),time=fights.reduce((n,x)=>n+x.durationMs,0),kills=fights.reduce((n,x)=>n+x.mobKillCount,0),player=fights.reduce((n,x)=>n+x.playerDamage,0),pet=fights.reduce((n,x)=>n+x.petDamage,0),best=Math.max(0,...fights.map(x=>x.dps)),bestHit=Math.max(0,...fights.map(x=>x.bestHit)); const map=new Map<string,{ability:string,cat:string,actorType:string,damage:number,hits:number,crits:number,best:number}>(),cats=new Map<string,number>(); for(const f of covered)for(const x of f.abilities){const cat=category(x),key=[x.actorType,norm(x.actor),norm(x.ability),cat].join('|'),v=map.get(key); if(v){v.damage+=x.damage;v.hits+=x.hits;v.crits+=x.criticalHits;v.best=Math.max(v.best,x.bestHit)}else map.set(key,{ability:x.ability,cat,actorType:x.actorType,damage:x.damage,hits:x.hits,crits:x.criticalHits,best:x.bestHit}); cats.set(cat,(cats.get(cat)||0)+x.damage)} const abilities=[...map.values()].sort((x,y)=>y.damage-x.damage),categories=[...cats].map(([name,damage])=>({name,damage})).sort((x,y)=>y.damage-x.damage); const targets=new Map<string,{name:string,fights:number,damage:number,time:number}>(); for(const x of fights){const k=norm(x.primaryNpcName),v=targets.get(k); if(v){v.fights++;v.damage+=x.totalDamage;v.time+=x.durationMs}else targets.set(k,{name:x.primaryNpcName,fights:1,damage:x.totalDamage,time:x.durationMs})} return{fights,covered,total,time,kills,player,pet,best,bestHit,dps:time?total/(time/1000):0,abilities,categories,targets:[...targets.values()].sort((x,y)=>y.fights-x.fights).slice(0,10)}} , [rows])
 if(loading)return <div className="analytics-page"><h2>Combat Analytics</h2><p>Loading persisted fights...</p></div>
 return <div className="analytics-page"><div className="analytics-heading"><div><span className="analytics-kicker">PLINKIFIED EQL</span><h2>Combat Analytics</h2><p>Persistent combat performance across saved encounters.</p></div><span className="analytics-version">v1</span></div>{error&&<div className="connection-warning">{error}</div>}<div className="analytics-coverage"><strong>Ability detail:</strong> {a.covered.length} of {a.fights.length} completed fights. Older fights still count in totals; detailed ability data begins with fights saved/replayed after Combat Analytics v1.</div><div className="analytics-summary-grid">{[['Fights',a.fights.length],['Kills',a.kills],['Combat Time',dur(a.time)],['Weighted DPS',a.dps.toFixed(1)],['Total Damage',a.total.toLocaleString()],['Your Damage',a.player.toLocaleString()],['Pet Damage',a.pet.toLocaleString()],['Best Fight DPS',a.best.toFixed(1)],['Best Hit',a.bestHit.toLocaleString()]].map(([k,v])=><div className="analytics-stat" key={String(k)}><span>{k}</span><strong>{v}</strong></div>)}</div><div className="analytics-columns"><section className="analytics-card"><h3>Damage Sources</h3><div className="analytics-source-list">{a.categories.map(x=><div className="analytics-source-row" key={x.name}><strong>{x.name}</strong><strong>{x.damage.toLocaleString()}</strong></div>)}</div></section><section className="analytics-card"><h3>Top Targets</h3><div className="analytics-target-list">{a.targets.map(x=><div className="analytics-target-row" key={x.name}><div><strong>{x.name}</strong><span>{x.fights} fights</span></div><strong>{(x.time?x.damage/(x.time/1000):0).toFixed(1)} DPS</strong></div>)}</div></section></div><section className="analytics-card"><h3>Abilities & Triggered Effects</h3><div className="analytics-table-wrap"><table className="analytics-table"><thead><tr><th>Ability / Effect</th><th>Type</th><th>Damage</th><th>Hits / Triggers</th><th>Crits</th><th>Best</th></tr></thead><tbody>{a.abilities.slice(0,40).map((x,i)=><tr key={i}><td><strong>{x.ability}</strong>{x.actorType==='pet'&&<span className="analytics-pet-tag">PET</span>}</td><td>{x.cat}</td><td>{x.damage.toLocaleString()}</td><td>{x.hits}</td><td>{x.crits}</td><td>{x.best.toLocaleString()}</td></tr>)}</tbody></table></div></section></div>
}
